name: Deploy React App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Dependencies
        working-directory: ./client
        run: npm ci
        
      - name: Create env file
        working-directory: ./client
        run: |
          touch .env
          echo "REACT_APP_OPENAI_API_KEY=${{ secrets.REACT_APP_OPENAI_API_KEY }}" >> .env
          cat .env
        
      - name: Build
        working-directory: ./client
        run: |
          npm run build
        env:
          REACT_APP_OPENAI_API_KEY: ${{ secrets.REACT_APP_OPENAI_API_KEY }}
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./client/build
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
